package leadwerks.support;

#if macro
import haxe.io.Path;
import haxe.macro.Compiler;
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type;
import sys.io.File;

using StringTools;
using haxe.macro.Tools;
using haxe.macro.TypeTools;
using haxe.macro.ExprTools;

private enum ScriptKind
{
	SNone;
	SEntity;
}

private enum LwPropType
{
	PBool;
	PInt;
	PFloat;
	PString;
	PVec3;
}

private typedef Callback =
{
	var name:String;
	var method:String;
	var args:Array<String>;
	var isVoid:Bool;
}

private typedef ScriptGen =
{
	var dir:String;
	var name:String;
	var tableName:String;
	var position:String;
	var properties:Array<{name:String, value:String, label:String}>;
	var callbacks:Array<Callback>;
	var cl:ClassType;
}

private class Glue
{
	static inline var EXPORT_TABLE = "_hxwerks_";

	public static function norm(p:String):String
		return StringTools.replace(p, "\\", "/");

	public static function absolutePath(relPath:String):String
	{
		if (Path.isAbsolute(relPath))
			return relPath;
		return Path.join([Sys.getCwd(), relPath]);
	}

	var outDir:String;
	var importLine:String;
	var scripts:Array<ScriptGen> = [];
	var baseEntityMethods:Map<String, Bool> = new Map();

	public function new(outDir:String, importLine:String)
	{
		this.outDir = outDir;
		this.importLine = importLine;
	}

	public function process(types:Array<ModuleType>)
	{
		for (type in types)
		{
			switch (type)
			{
				case TClassDecl(_.get() => cl):
					switch (cl)
					{
						case {pack: ["leadwerks", "support"], name: "EntityScript"}:
							for (field in cl.fields.get())
							{
								// Only lifecycle hooks, not helpers like `luaEntity`.
								if (field.name == "start" || field.name == "update")
									baseEntityMethods[field.name] = true;
							}
						case {params: [_]}:
						case _ if (cl.isAbstract):
						default:
							switch getScriptKind(cl)
							{
								case SEntity:
									// Ensure the script class is not removed by DCE, even if it is never referenced directly.
									// This lets users add new EntityScript subclasses without updating a manual `_keep` list.
									Compiler.keep((cl.pack.length == 0 ? "" : cl.pack.join(".") + ".") + cl.name);

									var props = getProperties(cl, cl.pos);
									props.sort((a, b) -> a.sortKey - b.sortKey);
									var posStr = Std.string(cl.pos);
									posStr = posStr.substring(5, posStr.length - 1);
									var scriptDir = Path.join([outDir].concat(cl.pack.copy()));
									scripts.push(
										{
											dir: scriptDir,
											name: cl.name + ".lua",
											tableName: cl.name,
											position: posStr,
											properties: [for (p in props) {name: p.name, value: p.value, label: p.label}],
											callbacks: [],
											cl: cl
										});
								default:
							}
					}
				default:
			}
		}

		if (scripts.length == 0)
			return;

		var initExprs:Array<Expr> = [];

		for (s in scripts)
		{
			var cl = s.cl;
			var exportExprs:Array<Expr> = [];
			var exportPrefix = (if (cl.pack.length == 0) cl.name else cl.pack.join("_") + "_" + cl.name) + "_";
			s.callbacks = generateCallbacksRecursive(cl, exportExprs, exportPrefix, baseEntityMethods);
			s.callbacks.sort((a, b) -> if (a.name == b.name) 0 else if (a.name < b.name) -1 else 1);

			var tp =
				{
					var parts = cl.module.split(".");
					parts.unshift("std");
					var name = parts.pop();
					{pack: parts, name: name, sub: cl.name};
				};

			initExprs.push(macro @:privateAccess {
				var script = new $tp();
				$b{exportExprs};
			});
		}

		if (initExprs.length > 0)
		{
			var td = macro class Init
				{
					static function init(exports:Dynamic)
						$b{initExprs};

					static function __init__()
					{
						untyped __lua__($v{EXPORT_TABLE + " = " + EXPORT_TABLE + " or {}"});
						init(untyped $i{EXPORT_TABLE});
					}
				};
			td.meta.push({name: ":keepInit", pos: td.pos});
			td.pack = ["leadwerks", "support"];
			Context.defineType(td);
		}
	}

	public function generate()
	{
		#if sys
		for (script in scripts)
		{
			var b = new StringBuf();
			b.add('-- Generated by Haxe (hxwerks), DO NOT EDIT (source: ${script.position})\n\n');
			b.add('${script.tableName} = {}\n\n');

			for (prop in script.properties)
			{
				b.add('${script.tableName}.${prop.name} = ${prop.value}--"${prop.label}"\n');
			}
			if (script.properties.length > 0)
				b.add("\n");

			b.add('${importLine}\n\n');

			for (cb in script.callbacks)
			{
				var methodArgs = cb.args.join(", ");
				// Leadwerks uses `function ScriptName:Start()` / `:Update(dt)` — `self` is implicit with `:`, do not list it.
				var luaParams = methodArgs;
				var call = '_G._hxwerks_.${cb.method}($methodArgs)';
				var cbName = luaCallbackName(cb.name);
				b.add('function ${script.tableName}:${cbName}(${luaParams})
    local _hxwerks_saved = ${EntityScriptBuilder.globalSelfRef}
    ${EntityScriptBuilder.globalSelfRef} = self
    ');
				if (cb.isVoid)
					b.add('    $call\n');
				else
					b.add('    local _hxwerks_ret = $call\n');
				b.add('    ${EntityScriptBuilder.globalSelfRef} = _hxwerks_saved\n');
				if (!cb.isVoid)
					b.add('    return _hxwerks_ret\n');
				b.add('end\n\n');
			}

			sys.FileSystem.createDirectory(script.dir);
			sys.io.File.saveContent(script.dir + "/" + script.name, b.toString());
		}
		#end
	}

	static function luaCallbackName(haxeMethod:String):String
	{
		return switch haxeMethod
		{
			case "start": "Start";
			case "update": "Update";
			default: Context.fatalError('unsupported entity script callback: $haxeMethod', Context.currentPos());
		}
	}

	function generateCallbacksRecursive(cl:ClassType, exportExprs:Array<Expr>, exportPrefix:String, baseMethods:Map<String, Bool>):Array<Callback>
	{
		var callbacks:Array<Callback> = [];

		for (baseName => _ in baseMethods)
		{
			var field = findLifecycleField(cl, baseName);
			if (field == null)
				continue;

			switch field.kind
			{
				case FMethod(_):
				default:
					continue;
			}

			switch Context.follow(field.type)
			{
				case TFun(args, ret):
					var argDefs = new Array<FunctionArg>();
					var argExprs = [];
					var argNames = [];
					for (a in args)
					{
						argNames.push(a.name);
						argDefs.push({name: a.name, type: macro :Dynamic});
						argExprs.push(macro $i{a.name});
					}
					var isVoid = isVoidType(ret);
					var fieldName = field.name;
					var expr = macro script.$fieldName($a{argExprs});
					if (!isVoid)
						expr = macro return $expr;
					var funExpr =
						{
							pos: field.pos,
							expr: EFunction(null,
								{
									args: argDefs,
									ret: null,
									expr: expr
								})
						};
					var exportName = exportPrefix + fieldName;
					exportExprs.push(macro exports.$exportName = $funExpr);
					callbacks.push(
						{
							name: fieldName,
							method: exportName,
							args: argNames,
							isVoid: isVoid
						});
				default:
					Context.fatalError("Entity script lifecycle field must be a method", field.pos);
			}
		}

		return callbacks;
	}

	/** Resolve override from subclass up to (including) `EntityScript`. */
	static function findLifecycleField(leaf:ClassType, name:String):ClassField
	{
		var c:Null<ClassType> = leaf;
		while (c != null)
		{
			for (f in c.fields.get())
			{
				if (f.name == name)
					return f;
			}
			c = c.superClass == null ? null : c.superClass.t.get();
		}
		return null;
	}

	static function isVoidType(t:Type):Bool
	{
		return switch Context.follow(t)
		{
			case TAbstract(_.get() => {name: "Void", pack: []}, _): true;
			case TEnum(_.get() => {name: "Void", pack: []}, _): true;
			default: false;
		}
	}

	static function getProperties(cl:ClassType, pos:Position):Array<
		{
			name:String,
			value:String,
			label:String,
			sortKey:Int
		}>
	{
		var properties:Array<
			{
				name:String,
				value:String,
				label:String,
				sortKey:Int
			}> = [];
		if (cl.superClass != null)
			properties = properties.concat(getProperties(cl.superClass.t.get(), pos));

		for (field in cl.fields.get())
		{
			switch field.kind
			{
				case FVar(_, _):
					var prop = field.meta.extract("property");
					switch prop
					{
						case [] | null:
						case [p]:
							var lt = getLwPropType(field.type, field.pos);
							var params = p.params != null ? p.params : [];
							var label:String;
							var value:String;
							if (params.length == 0)
							{
								label = defaultLabel(field.name);
								value = getDefaultValue(lt);
							} else
							{
								switch params[0].expr
								{
									case EConst(CString(s)):
										label = s;
										if (params.length >= 2) value = parsePropertyExpr(lt, params[1], field.pos); else value = getDefaultValue(lt);
									default:
										label = defaultLabel(field.name);
										value = parsePropertyExpr(lt, params[0], field.pos);
								}
							}
							var order = Context.getPosInfos(field.pos).min;
							properties.push(
								{
									name: field.name,
									value: value,
									label: label,
									sortKey: order
								});
						default:
							Context.fatalError("only one @property tag per field", pos);
					}
				default:
			}
		}
		return properties;
	}

	static function defaultLabel(fieldName:String):String
	{
		if (fieldName.length == 0)
			return fieldName;
		return fieldName.charAt(0).toUpperCase() + fieldName.substr(1);
	}

	static function getLwPropType(type:Type, pos:Position):LwPropType
	{
		var actual = type.follow();
		return switch actual
		{
			case TAbstract(_.get() => {pack: [], name: "Bool"}, _): PBool;
			case TAbstract(_.get() => {pack: [], name: "Int"}, _): PInt;
			case TAbstract(_.get() => {pack: [], name: "Float"}, _): PFloat;
			case TAbstract(_.get() => {pack: [], name: "String"}, _): PString;
			case TAbstract(_.get() => {pack: ["leadwerks", "types"], name: "Vec3"}, _): PVec3;
			case TAbstract(_.get() => t, _): getLwPropType(t.type, pos);
			default:
				Context.fatalError('Unsupported @property type: ${type.toString()}', pos);
		}
	}

	static function getDefaultValue(t:LwPropType):String
	{
		return switch t
		{
			case PBool: "false";
			case PInt: "0";
			case PFloat: "0.0";
			case PString: "''";
			case PVec3: "Vec3(0)";
		}
	}

	static function parsePropertyExpr(t:LwPropType, e:Expr, pos:Position):String
	{
		switch [t, e.expr]
		{
			case [PBool, EConst(CIdent(x = "true" | "false"))]:
				return x == "true" ? "true" : "false";
			case [PInt, EConst(CInt(n))]:
				return n;
			case [PFloat, EConst(CFloat(n))]:
				return n;
			case [PFloat, EConst(CInt(n))]:
				return n + ".0";
			case [PString, EConst(CString(s))]:
				return "'" + StringTools.replace(s, "'", "\\'") + "'";
			case [PVec3, ENew(c, el)] if (c.name == "Vec3"):
				return vec3FromArgs(el, pos);
			case [PVec3, ECall({expr: EConst(CIdent("Vec3"))}, el)]:
				return vec3FromArgs(el, pos);
			default:
				Context.fatalError("Invalid @property default expression for this type", pos);
				return "";
		}
	}

	static function vec3FromArgs(el:Array<Expr>, pos:Position):String
	{
		if (el.length == 0)
			return "Vec3(0)";
		var parts = [];
		for (x in el)
		{
			switch x.expr
			{
				case EConst(CFloat(n) | CInt(n)):
					parts.push(Std.string(n));
				default:
					Context.fatalError("Vec3 @property must use numeric literals", pos);
			}
		}
		while (parts.length < 3)
			parts.push("0");
		return 'Vec3(${parts[0]},${parts[1]},${parts[2]})';
	}

	static function getScriptKind(cl:ClassType):ScriptKind
	{
		return switch (cl)
		{
			case {superClass: {t: _.get() => {pack: ["leadwerks", "support"], name: "EntityScript"}}}: SEntity;
			case _ if (cl.superClass != null): getScriptKind(cl.superClass.t.get());
			default: SNone;
		}
	}

	static function isBaseEntityScriptType(cl:ClassType):Bool
	{
		return cl.pack.length == 2 && cl.pack[0] == "leadwerks" && cl.pack[1] == "support" && cl.name == "EntityScript";
	}
}

class ScriptMacro
{
	static var generated:Bool = false;

	/** Post-process the compiler output file to remove runtime `require()` dependencies. */
	static function patchOutputLua(outFile:String):Void
	{
		#if sys
		if (!sys.FileSystem.exists(outFile))
			return;
		var src = File.getContent(outFile);

		// Patch luv loader: avoid require("luv") if the runtime can't load modules.
		var luvNeedle = "if package.loaded.luv then";
		if (src.indexOf(luvNeedle) != -1)
		{
			var start = src.indexOf(luvNeedle);
			var endNeedle = "local _hx_static_init";
			var end = src.indexOf(endNeedle, start);
			if (end != -1)
			{
				var replacement = "-- Hxwerks patch: Leadwerks runtime may not support `require(\\\"luv\\\")` even if `package.loaded.luv` is present.\n"
					+ "-- Always probe with pcall(require) and fall back to a no-op loop.\n"
					+ "do\n"
					+ "  local okLuv = false\n"
					+ "  local luv = nil\n"
					+ "  if _G.require ~= nil then\n"
					+ "    okLuv, luv = pcall(_G.require, \"luv\")\n"
					+ "  end\n"
					+ "  if okLuv and luv ~= nil then\n"
					+ "    _hx_luv = luv\n"
					+ "  else\n"
					+ "    _hx_luv = { run=function(mode) return false end, loop_alive=function() return false end }\n"
					+ "  end\n"
					+ "end\n";
				// keep `local _hx_static_init...` but remove the whole original luv block (including its trailing `end`).
				src = src.substring(0, start) + replacement + src.substring(end);
			}
		}

		// Patch bit loader: avoid hard error when both bit/bit32 modules are absent.
		var bitNeedle = "local hasBit32, bit32 = pcall(require, 'bit32')";
		if (src.indexOf(bitNeedle) != -1)
		{
			var start = src.indexOf(bitNeedle);
			var endNeedle = "-- see https://github.com/HaxeFoundation/haxe/issues/8849";
			var end = src.indexOf(endNeedle, start);
			if (end != -1)
			{
				var replacement = "-- Hxwerks patch: Leadwerks runtime may not ship `bit`/`bit32` modules.\n"
					+ "-- Prefer globals, otherwise use native bitops on Lua 5.3+.\n"
					+ "local _hx_bit_raw = nil\n"
					+ "local _hx_bit = nil\n"
					+ "if _G.bit32 ~= nil then\n"
					+ "  _hx_bit_raw = _G.bit32\n"
					+ "elseif _G.bit ~= nil then\n"
					+ "  _hx_bit_raw = _G.bit\n"
					+ "else\n"
					+ "  local ok32, bit32 = pcall(require, 'bit32')\n"
					+ "  if ok32 then\n"
					+ "    _hx_bit_raw = bit32\n"
					+ "  else\n"
					+ "    local okBit, bit = pcall(require, 'bit')\n"
					+ "    if okBit then\n"
					+ "      _hx_bit_raw = bit\n"
					+ "    else\n"
					+ "      local okNative = false\n"
					+ "      local chunk = load('return 1|2')\n"
					+ "      if type(chunk) == 'function' then okNative = pcall(chunk) end\n"
					+ "      if not okNative then error('Failed to load bit/bit32 and native bitops are unavailable') end\n"
					+ "      _hx_bit_raw = {\n"
					+ "        bor=function(a,b) return (a | b) end,\n"
					+ "        band=function(a,b) return (a & b) end,\n"
					+ "        bnot=function(a) return (~a) end,\n"
					+ "        bxor=function(a,b) return (a ~ b) end,\n"
					+ "        arshift=function(a,b) return (a >> b) end,\n"
					+ "      }\n"
					+ "    end\n"
					+ "  end\n"
					+ "end\n"
					+ "_hx_bit = setmetatable({}, { __index = _hx_bit_raw })\n"
					+ "_hx_bit.bnot = function(...) return _hx_bit_clamp(_hx_bit_raw.bnot(...)) end\n"
					+ "_hx_bit.bxor = function(...) return _hx_bit_clamp(_hx_bit_raw.bxor(...)) end\n";
				src = src.substring(0, start) + replacement + src.substring(end);
			}
		}

		// Patch final xpcall handler to print the error message.
		var tailNeedle = "if not success then _G.error(err) end";
		if (src.indexOf(tailNeedle) != -1)
		{
			src = src.replace(tailNeedle,
				"if not success then\n"
				+ "  local msg = tostring(err)\n"
				+ "  if _G.Print then\n"
				+ "    _G.Print(msg)\n"
				+ "  elseif _G.print then\n"
				+ "    _G.print(msg)\n"
				+ "  end\n"
				+ "  _G.error(msg)\n"
				+ "end");
		}

		File.saveContent(outFile, src);
		#end
	}

	static function use()
	{
		// Runs for any `-lib hxwerks` build (including `haxelib run`). Only apply Lua glue when output is a .lua file.
		if (generated)
			return;
		var rawOut = Compiler.getOutput();
		if (rawOut == null || StringTools.trim(rawOut) == "")
			return;
		if (!StringTools.endsWith(rawOut.toLowerCase(), ".lua"))
			return;
		generated = true;

		var projectRoot = Context.definedValue("hxwerks-projectroot");
		if (projectRoot == null)
			projectRoot = ".";

		var entitiesDir = Context.definedValue("hxwerks-entitiesdir");
		if (entitiesDir == null)
			entitiesDir = "Entities/HxGen";

		projectRoot = Glue.absolutePath(projectRoot);
		if (!projectRoot.endsWith("/") && !projectRoot.endsWith("\\"))
			projectRoot += "/";

		var outFile = Glue.absolutePath(rawOut);
		if (!StringTools.startsWith(Glue.norm(outFile), Glue.norm(projectRoot)))
		{
			Context.fatalError("Haxe Lua output must be inside hxwerks-projectroot (" + projectRoot + "), but is " + outFile, Context.currentPos());
		}

		var outDir = Path.join([projectRoot, entitiesDir]);

		var rel = outFile.substring(projectRoot.length);
		rel = StringTools.replace(rel, "\\", "/");
		var parts = rel.split("/");
		var last = parts.length - 1;
		parts[last] = Path.withoutExtension(parts[last]);
		rel = parts.join("/");

		var useImport = Context.definedValue("hxwerks-use-import");
		var importLine = switch useImport
		{
			case null | "false": "";
			case "import": 'import "${rel}.lua"';
			case "require": 'require "${parts.join(".")}"';
			case v: '${v}';
		};

		var glue = new Glue(outDir, importLine);
		var done = false;
		Context.onAfterTyping(function(types)
		{
			if (done)
				return;
			if (!Context.defined("lua"))
			{
				done = true;
				return;
			}
			done = true;
			glue.process(types);
		});
		Context.onAfterGenerate(function()
		{
			if (Context.defined("lua"))
			{
				glue.generate();
				patchOutputLua(outFile);
			}
		});
	}
}
#end
